import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { getDashboardSummary, getMyAgendamentos } from '../../api';
import { useUnitSelection } from '../../hooks/useUnitSelection';
import { useAdminAuth } from '../../stores/authStore';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/Card';
import { Badge, getStatusBadge } from '../../components/ui/Badge';
import { Calendar, Users, DollarSign, Clock, CheckCircle, MapPin, RefreshCw } from 'lucide-react';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
export function AdminDashboard() {
    const { selectedUnitId, selectedUnit, unidades, setSelectedUnitId } = useUnitSelection();
    const { user } = useAdminAuth();
    const { data: summary, isLoading: loadingSummary, isError, refetch } = useQuery({
        queryKey: ['dashboard-summary', selectedUnitId],
        queryFn: () => getDashboardSummary(selectedUnitId ?? undefined),
        enabled: !!selectedUnitId,
    });
    const { data: appointmentsData } = useQuery({
        queryKey: ['dashboard-appointments', selectedUnitId],
        queryFn: () => getMyAgendamentos(1, 5, 'Confirmado', selectedUnitId ?? undefined),
        enabled: !!selectedUnitId,
    });
    const upcomingAppointments = appointmentsData?.items || appointmentsData || [];
    const todayStr = format(new Date(), "EEEE, dd 'de' MMMM", { locale: ptBR });
    const stats = [
        { label: 'Agendamentos Hoje', value: summary?.totalHoje ?? 0, icon: Calendar, color: 'bg-blue-500' },
        { label: 'Pendentes', value: summary?.pendentes ?? 0, icon: Clock, color: 'bg-yellow-500' },
        { label: 'Finalizados (Mês)', value: summary?.finalizadosMes ?? 0, icon: CheckCircle, color: 'bg-green-500' },
        { label: 'Faturamento (Mês)', value: `R$ ${(summary?.faturamentoMes ?? 0).toFixed(2)}`, icon: DollarSign, color: 'bg-emerald-500' },
    ];
    return (_jsxs("div", { children: [_jsxs("div", { className: "flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6", children: [_jsxs("div", { children: [_jsxs("h1", { className: "text-2xl font-bold text-gray-900", children: ["Ol\u00E1, ", user?.nome?.split(' ')[0] || 'Admin', "!"] }), _jsx("p", { className: "text-sm text-gray-500 capitalize mt-1", children: todayStr })] }), unidades.length > 1 && (_jsx("select", { className: "px-3 py-2 border border-gray-300 rounded-lg text-sm bg-white", value: selectedUnitId ?? '', onChange: (e) => setSelectedUnitId(Number(e.target.value)), children: unidades.map((u) => (_jsx("option", { value: u.id, children: u.name }, u.id))) }))] }), isError && (_jsxs("div", { className: "bg-red-50 border border-red-200 rounded-lg p-4 mb-6 flex items-center justify-between", children: [_jsx("p", { className: "text-sm text-red-700", children: "Erro ao carregar dados do dashboard." }), _jsxs("button", { onClick: () => refetch(), className: "flex items-center gap-1 text-sm text-red-600 hover:text-red-700", children: [_jsx(RefreshCw, { className: "w-4 h-4" }), " Tentar novamente"] })] })), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8", children: stats.map((stat) => (_jsx("div", { className: "bg-white rounded-xl shadow-sm border border-gray-100 p-6", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm text-gray-500", children: stat.label }), _jsx("p", { className: "text-2xl font-bold text-gray-900 mt-1", children: loadingSummary ? (_jsx("span", { className: "inline-block w-16 h-7 bg-gray-200 rounded animate-pulse" })) : (stat.value) })] }), _jsx("div", { className: `${stat.color} p-3 rounded-lg`, children: _jsx(stat.icon, { className: "w-6 h-6 text-white" }) })] }) }, stat.label))) }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-6", children: [_jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(Calendar, { className: "w-5 h-5 text-blue-600" }), "Pr\u00F3ximos Agendamentos"] }) }), _jsx(CardContent, { children: loadingSummary ? (_jsx("div", { className: "space-y-3", children: Array.from({ length: 3 }).map((_, i) => (_jsx("div", { className: "h-16 bg-gray-100 rounded-lg animate-pulse" }, i))) })) : Array.isArray(upcomingAppointments) && upcomingAppointments.length > 0 ? (_jsxs("div", { className: "space-y-3", children: [upcomingAppointments.slice(0, 5).map((apt) => {
                                            const badge = getStatusBadge(apt.statusName || apt.status?.toString() || '');
                                            return (_jsxs("div", { className: "flex items-center justify-between p-3 bg-gray-50 rounded-lg", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center", children: _jsx(Users, { className: "w-5 h-5 text-blue-600" }) }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-gray-900", children: apt.clientName || 'Cliente' }), _jsx("p", { className: "text-sm text-gray-500", children: apt.servicoName || 'Serviço' })] })] }), _jsxs("div", { className: "text-right", children: [_jsx("span", { className: "text-sm text-blue-600 font-medium", children: apt.scheduledAt ? format(new Date(apt.scheduledAt), 'HH:mm') : '--:--' }), _jsx("div", { className: "mt-1", children: _jsx(Badge, { variant: badge.variant, children: badge.label }) })] })] }, apt.id));
                                        }), _jsx("a", { href: "/admin/agendamentos", className: "text-sm text-blue-600 hover:text-blue-700 font-medium", children: "Ver todos os agendamentos \u2192" })] })) : (_jsxs("div", { className: "text-center py-8 text-gray-500", children: [_jsx(Calendar, { className: "w-12 h-12 mx-auto mb-2 text-gray-300" }), _jsx("p", { children: "Nenhum agendamento confirmado" })] })) })] }), _jsxs(Card, { children: [_jsx(CardHeader, { children: _jsxs(CardTitle, { className: "flex items-center gap-2", children: [_jsx(MapPin, { className: "w-5 h-5 text-blue-600" }), "Informa\u00E7\u00F5es da Unidade"] }) }), _jsx(CardContent, { children: selectedUnit ? (_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "font-semibold text-gray-900", children: selectedUnit.name }), _jsx("p", { className: "text-sm text-gray-500 mt-1", children: selectedUnit.address }), _jsxs("p", { className: "text-sm text-gray-500", children: [selectedUnit.city, ", ", selectedUnit.state] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-4", children: [_jsxs("div", { className: "bg-gray-50 rounded-lg p-3", children: [_jsx("p", { className: "text-xs text-gray-500", children: "Status" }), _jsx("p", { className: `text-sm font-medium ${selectedUnit.published ? 'text-green-600' : 'text-yellow-600'}`, children: selectedUnit.published ? 'Publicado' : 'Não publicado' })] }), _jsxs("div", { className: "bg-gray-50 rounded-lg p-3", children: [_jsx("p", { className: "text-xs text-gray-500", children: "Avalia\u00E7\u00E3o" }), _jsx("p", { className: "text-sm font-medium text-gray-900", children: selectedUnit.averageRating ? `${selectedUnit.averageRating.toFixed(1)} ★` : 'Sem avaliações' })] }), _jsxs("div", { className: "bg-gray-50 rounded-lg p-3", children: [_jsx("p", { className: "text-xs text-gray-500", children: "Leva e Traz" }), _jsx("p", { className: "text-sm font-medium text-gray-900", children: selectedUnit.ofereceLevaTraz ? 'Sim' : 'Não' })] }), _jsxs("div", { className: "bg-gray-50 rounded-lg p-3", children: [_jsx("p", { className: "text-xs text-gray-500", children: "Telefone" }), _jsx("p", { className: "text-sm font-medium text-gray-900", children: selectedUnit.phone || 'Não informado' })] })] }), _jsx("a", { href: "/admin/unidades", className: "text-sm text-blue-600 hover:text-blue-700 font-medium", children: "Gerenciar unidade \u2192" })] })) : (_jsxs("div", { className: "text-center py-8 text-gray-500", children: [_jsx(MapPin, { className: "w-12 h-12 mx-auto mb-2 text-gray-300" }), _jsx("p", { children: "Nenhuma unidade selecionada" })] })) })] })] })] }));
}
