import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { api } from '../../api/client';
import { Building2, MapPin } from 'lucide-react';
export default function MasterUnidades() {
    const { data: unidades, isLoading } = useQuery({
        queryKey: ['all-unidades'],
        queryFn: async () => (await api.get('/unidades')).data,
    });
    return (_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 mb-6", children: "Todas as Unidades" }), _jsx("div", { className: "bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden", children: isLoading ? _jsx("div", { className: "p-8 text-center text-gray-400", children: "Carregando..." }) : !unidades?.length ? (_jsxs("div", { className: "p-8 text-center", children: [_jsx(Building2, { className: "w-12 h-12 text-gray-300 mx-auto mb-3" }), _jsx("p", { className: "text-gray-500", children: "Nenhuma unidade encontrada" })] })) : (_jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-gray-50 border-b border-gray-100", children: _jsxs("tr", { children: [_jsx("th", { className: "text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase", children: "Nome" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase", children: "Endere\u00E7o" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase", children: "Hor\u00E1rio" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase", children: "Status" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: unidades.map((u) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 font-medium text-gray-900", children: u.nome }), _jsxs("td", { className: "px-6 py-4 text-sm text-gray-600 flex items-center gap-1", children: [_jsx(MapPin, { className: "w-3 h-3" }), u.endereco || '—'] }), _jsxs("td", { className: "px-6 py-4 text-sm text-gray-600", children: [u.horarioAbertura, " - ", u.horarioFechamento] }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `px-2 py-1 text-xs rounded-full font-medium ${u.ativo ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`, children: u.ativo ? 'Ativo' : 'Inativo' }) })] }, u.id))) })] })) })] }));
}
