import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useQuery } from '@tanstack/react-query';
import { api } from '../../api/client';
import { Users, Search } from 'lucide-react';
import { useState } from 'react';
export default function MasterUsuarios() {
    const [search, setSearch] = useState('');
    const { data: usuarios, isLoading } = useQuery({
        queryKey: ['all-users', search],
        queryFn: async () => (await api.get('/admin/users', { params: { search } })).data,
    });
    return (_jsxs("div", { children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900 mb-6", children: "Usu\u00E1rios" }), _jsxs("div", { className: "relative mb-6", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" }), _jsx("input", { value: search, onChange: (e) => setSearch(e.target.value), placeholder: "Buscar usu\u00E1rio...", className: "w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-slate-500 outline-none" })] }), _jsx("div", { className: "bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden", children: isLoading ? _jsx("div", { className: "p-8 text-center text-gray-400", children: "Carregando..." }) : !usuarios?.length ? (_jsxs("div", { className: "p-8 text-center", children: [_jsx(Users, { className: "w-12 h-12 text-gray-300 mx-auto mb-3" }), _jsx("p", { className: "text-gray-500", children: "Nenhum usu\u00E1rio encontrado" })] })) : (_jsxs("table", { className: "w-full", children: [_jsx("thead", { className: "bg-gray-50 border-b border-gray-100", children: _jsxs("tr", { children: [_jsx("th", { className: "text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase", children: "Nome" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase", children: "Email" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase", children: "Tipo" }), _jsx("th", { className: "text-left px-6 py-3 text-xs font-medium text-gray-500 uppercase", children: "Status" })] }) }), _jsx("tbody", { className: "divide-y divide-gray-100", children: usuarios.map((u) => (_jsxs("tr", { className: "hover:bg-gray-50", children: [_jsx("td", { className: "px-6 py-4 font-medium text-gray-900", children: u.nome }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-600", children: u.email }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: "px-2 py-1 bg-slate-100 text-slate-700 text-xs rounded-full font-medium", children: u.tipo }) }), _jsx("td", { className: "px-6 py-4", children: _jsx("span", { className: `px-2 py-1 text-xs rounded-full font-medium ${u.ativo ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`, children: u.ativo ? 'Ativo' : 'Inativo' }) })] }, u.id))) })] })) })] }));
}
